import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: ['src/**/*.ts'],
  outDir: 'dist',
  format: {
    esm: {
      target: ['es2022'],
    },
  },
  dts: true,
  sourcemap: false,
  clean: true,
  external: [
    'zod',
    'es-toolkit',
    '@pcontext/shared',
    'hono',
    'hono/*',
    '@hono/node-server',
    '@hono/vite-dev-server',
    '@hono/zod-validator',
    '@libsql/client',
    'drizzle-orm',
    'drizzle-zod',
    'ai',
    'llamaindex',
    '@llamaindex/*',
    '@ai-sdk/llamaindex',
    '@llamaindex/openai',
    '@llamaindex/readers',
    '@llamaindex/tools',
    '@llamaindex/workflow',
    '@llamaindex/milvus',
    '@mendable/firecrawl-js',
    '@modelcontextprotocol/sdk',
    '@zilliz/milvus2-sdk-node',
    'argon2',
    'bullmq',
    'casbin',
    'croner',
    'cross-env',
    'dotenv',
    'ioredis',
    'isbot',
    'katex',
    'pg',
    'pino',
    'pino-http',
    'stoker',
    'uuidv7',
  ],
})
